cabal-version: 3.8
name: herbrand
version: 0.1.0.0
synopsis: Propositional logic tools and SAT solvers
description: Please see the README on GitHub at <https://github.com/konn/herbrand#readme>
category: Logic
homepage: https://github.com/konn/herbrand#readme
bug-reports: https://github.com/konn/herbrand/issues
author: Hiromi ISHII
maintainer: konn.jinro_at_gmail.com
copyright: 2023 (c) Hiromi ISHII
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple
tested-with:
  ghc ==9.12.4 || ==9.14.1

extra-doc-files:
  CHANGELOG.md
  README.md

extra-source-files:
  data/satlib/uf20-91-full/*.cnf

source-repository head
  type: git
  location: https://github.com/konn/herbrand

flag bench-chart
  description: Whether to build bench-chart or not
  manual: True
  default: False

common defaults
  default-language: Haskell2010
  other-modules:
    Paths_herbrand

  autogen-modules:
    Paths_herbrand

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
    -flate-dmd-anal

  build-depends:
    aeson,
    attoparsec,
    base >=4.7 && <5,
    bifunctors,
    bytestring,
    containers,
    data-fix,
    deepseq,
    distributive,
    dlist,
    filtrable,
    fmlist,
    foldable1-classes-compat,
    foldl,
    generic-lens,
    generically,
    hashable,
    integer-logarithms,
    lens,
    parallel,
    psqueues,
    random,
    recursion-schemes,
    reflection,
    semigroupoids,
    strict,
    text,
    transformers,
    trie-simple,
    unordered-containers,
    vector,

library
  import: defaults
  -- cabal-gild: discover src --exclude=src/**/Internal.hs --exclude=src/**/Internal/**/*.hs
  exposed-modules:
    Control.Foldl.Linear
    Control.Functor.Linear.State.Extra
    Data.HashMap.Mutable.Linear.Extra
    Data.Matrix.Mutable.Linear.Unboxed
    Data.Monoid.Linear.Orphans
    Data.Set.Mutable.Linear.Extra
    Data.Unrestricted.Linear.Orphans
    Data.Vector.Mutable.Linear.Helpers
    Debug.Trace.Lienar.Extra
    Logic.Propositional.Classical.SAT.BruteForce
    Logic.Propositional.Classical.SAT.CDCL
    Logic.Propositional.Classical.SAT.CDCL.Types
    Logic.Propositional.Classical.SAT.DPLL
    Logic.Propositional.Classical.SAT.Format.DIMACS
    Logic.Propositional.Classical.SAT.Tableaux
    Logic.Propositional.Classical.SAT.Types
    Logic.Propositional.Syntax.General
    Logic.Propositional.Syntax.NormalForm.Classical.Conjunctive
    Logic.Propositional.Syntax.NormalForm.Classical.Conjunctive.Sudoku
    Logic.Propositional.Syntax.Transformation.Claassical

  -- cabal-gild: discover src --include=src/**/Internal.hs --include=src/**/Internal/**/*.hs
  other-modules:
  hs-source-dirs:
    src

  build-tool-depends:
    cabal-gild:cabal-gild >=1.6.0.0

  build-depends:
    bitvec,
    derive-storable,
    derive-storable-plugin,
    linear-array-extra,
    linear-base,
    linear-generics,
    linear-memory,
    linear-witness,
    vector-th-unbox,

library herbrand-bench
  import: defaults
  -- cabal-gild: discover libs/bench
  exposed-modules:
    Herbrand.Bench

  hs-source-dirs:
    libs/bench

  build-depends:
    Glob,
    directory,
    filepath,
    herbrand,
    safe-exceptions,
    tasty,
    tasty-bench,
    tasty-expected-failure,

library herbrand-test-utils
  import: defaults
  -- cabal-gild: discover libs/test
  exposed-modules:
    Herbrand.Test

  hs-source-dirs:
    libs/test

  build-depends:
    directory,
    falsify,
    filepath,
    herbrand,
    tasty,

executable bench-chart
  import: defaults
  main-is: Main.hs
  -- cabal-gild: discover app/bench-chart --exclude=app/bench-chart/Main.hs
  other-modules:
    Pages
    Parse
    Plot
    Report
    Types
    Units

  hs-source-dirs:
    app/bench-chart

  ghc-options:
    "-with-rtsopts=--nonmoving-gc -N8"
    -fproc-alignment=64
    -O2
    -rtsopts
    -threaded

  build-depends:
    Glob,
    blaze-markup,
    cassava,
    chart-svg,
    directory,
    filepath,
    githash,
    herbrand,
    lucid2,
    optparse-applicative,
    path,
    path-io,
    semialign,
    these,
    time,
    unliftio,

  if flag(bench-chart)
    buildable: True
  else
    buildable: False

executable cdcl-dry
  import: defaults
  main-is: Main.hs
  hs-source-dirs:
    app/cdcl-dry

  ghc-options:
    -with-rtsopts=--nonmoving-gc
    -fproc-alignment=64
    -O2
    -rtsopts

  build-depends:
    herbrand,
    optparse-applicative,

executable gen-sat
  import: defaults
  main-is: Main.hs
  hs-source-dirs:
    app/gen-sat

  ghc-options:
    -O2

  build-depends:
    directory,
    falsify,
    filepath,
    herbrand,
    herbrand:herbrand-test-utils,
    optparse-applicative,
    parser-combinators,

executable sudoku
  import: defaults
  main-is: Main.hs
  hs-source-dirs:
    app/sudoku

  ghc-options:
    -O2

  build-depends:
    directory,
    filepath,
    herbrand,
    optparse-applicative,
    parser-combinators,

test-suite herbrand-test
  import: defaults
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  -- cabal-gild: discover test --exclude=test/Spec.hs
  other-modules:
    Logic.Propositional.Classical.SAT.CDCLSpec
    Logic.Propositional.Classical.SAT.DPLLSpec
    Logic.Propositional.Classical.SAT.TableauxSpec
    Logic.Propositional.Classical.Syntax.TestUtils
    Logic.Propositional.Syntax.NormalForm.Classical.ConjunctiveSpec

  hs-source-dirs:
    test

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N
    -O2

  build-tool-depends:
    tasty-discover:tasty-discover

  build-depends:
    directory,
    falsify,
    filepath,
    filepattern,
    herbrand,
    herbrand:herbrand-test-utils,
    tasty,
    tasty-hunit,
    tasty-quickcheck,

benchmark herbrand-cnf-bench
  import: defaults
  type: exitcode-stdio-1.0
  main-is: cnf.hs
  hs-source-dirs:
    bench

  ghc-options:
    "-with-rtsopts=-A32m -T --nonmoving-gc"
    -fproc-alignment=64
    -O2

  build-tool-depends:
    tasty-discover:tasty-discover

  build-depends:
    directory,
    falsify,
    filepath,
    herbrand,
    herbrand:herbrand-bench,
    tasty,
    tasty-bench,
    tasty-bench-fit,
    tasty-expected-failure,

  buildable: False

benchmark herbrand-sat-bench
  import: defaults
  type: exitcode-stdio-1.0
  main-is: sat.hs
  hs-source-dirs:
    bench

  ghc-options:
    "-with-rtsopts=-A32m -T --nonmoving-gc"
    -fproc-alignment=64
    -O2

  build-tool-depends:
    tasty-discover:tasty-discover

  build-depends:
    directory,
    falsify,
    filepath,
    herbrand,
    herbrand:herbrand-bench,
    tasty,
    tasty-bench,
    tasty-bench-fit,
    tasty-expected-failure,
