name:                herbrand
version:             0.1.0.0
github:              "konn/herbrand"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro_at_gmail.com"
copyright:           "2023 (c) Hiromi ISHII"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/herbrand#readme>

dependencies:
- base >= 4.7 && < 5
- adjunctions
- aeson
- attoparsec
- algebraic-graphs
- bifunctors
- bytestring
- lens
- containers
- data-fix
- deepseq
- distributive
- dlist
- filtrable
- fmlist
- foldable1-classes-compat
- foldl
- generic-lens
- hashable
- parallel
- recursion-schemes
- rec-def
- semigroupoids
- strict
- transformers
- text
- unordered-containers
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
  - Logic.Propositional.Classical.SAT.CDCL.Types
  dependencies:
  - bitvec
  - linear-array-extra
  - linear-base
  - linear-generics
  - vector-th-unbox

internal-libraries:
  herbrand-bench:
    source-dirs: libs/bench
    dependencies:
    - herbrand
    - directory
    - filepath
    - Glob
    - safe-exceptions
    - tasty
    - tasty-bench
    - tasty-expected-failure

  herbrand-test-utils:
    source-dirs: libs/test
    dependencies:
    - herbrand
    - directory
    - filepath
    - tasty
    - falsify

executables:
  gen-sat:
    main:                Main.hs
    source-dirs:         app/gen-sat
    ghc-options:
    - -O2
    dependencies:
    - herbrand
    - herbrand-test-utils
    - bytestring
    - directory
    - falsify
    - filepath
    - optparse-applicative
    - parser-combinators

  cdcl-dry:
    main:                Main.hs
    source-dirs:         app/cdcl-dry
    ghc-options:
    - '"-with-rtsopts=-A32m -T --nonmoving-gc"'
    - -fproc-alignment=64
    - -O2
    dependencies:
    - herbrand
    - herbrand-test-utils
    - bytestring
    - directory
    - falsify
    - filepath
    - optparse-applicative
    - parser-combinators

tests:
  herbrand-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    build-tools:
    - tasty-discover
    dependencies:
    - herbrand
    - herbrand-test-utils
    - tasty
    - falsify
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  herbrand-cnf-bench:
    main:                cnf.hs
    source-dirs:         bench
    ghc-options:
    - '"-with-rtsopts=-A32m -T --nonmoving-gc"'
    - -fproc-alignment=64
    - -O2
    build-tools:
    - tasty-discover
    dependencies:
    - herbrand
    - herbrand-bench
    - directory
    - filepath
    - tasty
    - falsify
    - tasty-bench
    - tasty-bench-fit
    - tasty-expected-failure

  herbrand-sat-bench:
    main:                sat.hs
    source-dirs:         bench
    ghc-options:
    - '"-with-rtsopts=-A32m -T --nonmoving-gc"'
    - -fproc-alignment=64
    - -O2
    build-tools:
    - tasty-discover
    dependencies:
    - herbrand
    - herbrand-bench
    - directory
    - filepath
    - tasty
    - falsify
    - tasty-bench
    - tasty-bench-fit
    - tasty-expected-failure
