name:                herbrand
version:             0.1.0.0
github:              "konn/herbrand"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro_at_gmail.com"
copyright:           "2023 (c) Hiromi ISHII"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/herbrand#readme>

dependencies:
- base >= 4.7 && < 5
- algebraic-graphs
- bifunctors
- bytestring
- lens
- linear-base
- containers
- data-fix
- deepseq
- distributive
- dlist
- filtrable
- fmlist
- foldable1-classes-compat
- foldl
- generic-lens
- hashable
- parallel
- recursion-schemes
- rec-def
- strict
- transformers
- text
- unordered-containers
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  herbrand-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - herbrand

tests:
  herbrand-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tasty-discover
    dependencies:
    - herbrand
    - tasty
    - falsify
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  herbrand-cnf-bench:
    main:                cnf.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tasty-discover
    dependencies:
    - herbrand
    - tasty
    - falsify
    - tasty-bench
    - tasty-bench-fit

  herbrand-sat-bench:
    main:                sat.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tasty-discover
    dependencies:
    - herbrand
    - tasty
    - falsify
    - tasty-bench
    - tasty-bench-fit

